### ISSUE TITLE
Data to experiment with FRE7241_Lecture_2.R file

### ISSUE THREAD

**Issue by MislavSag** [algoquant/lecture_slides#2]
Hello,

I have discovered your lectures on FRE7241 Algorithmic Portfolio Management.

I have skimmed first lectureand started second.

There is a file in row 7 of the code (https://github.com/algoquant/lecture_slides/blob/master/FRE7241_Lecture_2.R):
```
etflist <- read.csv(file="/Users/jerzy/Develop/lecture_slides/data/etf_list.csv")
```
Is this data publicly avaialble?

I have my own data, but would be much easier to reproduce the code with same data.

**Comment by algoquant** [comment]
@MislavSag 
Please send me your email address to jp3900@nyu.edu
And I will give you access to my repo.

**Comment by MislavSag** [comment]
Email: mislav.sagovac@contentio.biz

Thanks!
